feat: CRUD api implemented
mcksyrek/booking-platform-server pull request #2
Opened 2020-10-18 20:45 UTC by mcksyrek

2020-10-19 22:25 UTC, ArtemLunt requested changes

2020-10-19 22:25 UTC, ArtemLunt commented on src/main/java/com/bookingplatform/server/offer/OfferService.java
> +            throw new ResourceNotFoundException("offer");
Also, as i know, we can throw the http error with no any magic:
https://www.baeldung.com/spring-response-status-exception#:~:text=ResponseStatus&text=This%20annotation%20was%20introduced%20in,code%20to%20an%20HTTP%20response.&text=If%20this%20exception%20is%20thrown,status%20specified%20in%20this%20annotation.

2020-10-20 09:26 UTC, mcksyrek commented on src/main/resources/application.yml
> +      ddl-auto: none
currently I am working on layout and that is irritating that after every reset of BE I have to create mock data again and again. any other ideas how to resolve that issue?

2020-10-20 18:35 UTC, mcksyrek commented on src/main/resources/application.yml
> +      ddl-auto: none
ahh, ok got it - `none` will not make any changes if I change `@Entity`
changed to `update`

2020-10-20 18:41 UTC, ArtemLunt commented on src/main/resources/application.yml
> +      ddl-auto: none
Exactly )

2020-10-20 19:48 UTC, ArtemLunt requested changes

2020-10-20 19:48 UTC, ArtemLunt commented on src/main/java/com/bookingplatform/server/offer/OfferService.java
> +            updatedOffer.setName(offer.getName());
Doesn't seems to be extensible.
I guess we can simply save original object.

2020-10-20 20:27 UTC, merged

2020-10-20 20:28 UTC, ArtemLunt approved these changes